language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.1

android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

before_install:
  - openssl aes-256-cbc -K $encrypted_3c9089ac5e40_key -iv $encrypted_3c9089ac5e40_iv -in weather.jks.enc -out weather.jks -d

script:
  - chmod a+x ./gradlew
  - "./gradlew build check"
