name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make SDK folders (licenses, build-tools, .temp) writable
        run: sudo mkdir -p /usr/local/lib/android/sdk/{licenses,build-tools,.temp} && sudo chmod -R 777 /usr/local/lib/android/sdk/{licenses,build-tools,.temp}

      - name: Make gradlew executable
        run: chmod a+x gradlew

      - name: Build
        env:
          OPENWEATHERMAP_KEY: ${{ secrets.OPENWEATHERMAP_KEY }}
        run: ./gradlew assembleDebug lint test

      - name: Upload build artifacts
        uses: actions/upload-artifact@master
        with:
          name: apks-artifacts
          path: app/build/outputs/apk
      
      - name: Upload reports
        uses: actions/upload-artifact@master
        with:
          name: reports
          path: app/build/reports

      - name: Upload test results
        uses: actions/upload-artifact@master
        with:
          name: test-results
          path: app/build/test-results